accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
	path('register/', views.register, name='register'),
	path('login/', views.login_request, name='login'),
	path('logout/', views.logout_request, name='logout'),
]

camper/urls.py
from django.urls import path, include
from .views import index, camper_list, camper_form_new, camper_form_update, camper_delete, dashboard

app_name = 'camper'

urlpatterns = [
    path('', index, name='home'),
    path('campers/list/', camper_list, name='list'),
    path('campers/new/', camper_form_new, name='form'),
    path('campers/<int:id>/', camper_form_update, name='update'),
    path('campers/delete/<int:id>/', camper_delete, name='delete'),
    path('dashboard', dashboard, name='dashboard'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('camper.urls')),
    path('', include('accounts.urls')),
]

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'camper:home' %}">CampStar</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'camper:home' %}">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'camper:list' %}">Campers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'camper:dashboard' %}">Dashboard</a>
      </li>
      <li class="nav-item">
        {% if request.user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a>
        {% else %}
        <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
        {% endif %}
      </li>
    </ul>
  </div>
</nav>

templates/partials/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}