accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
	path('register/', views.register, name='register'),
	path('login/', views.login_request, name='login'),
	path('logout/', views.logout_request, name='logout'),
]

camper/urls.py
from django.urls import path, include
from .views import index, camper_list, camper_form_new, camper_form_update, camper_delete, dashboard

app_name = 'camper'

urlpatterns = [
    path('', index, name='home'),
    path('campers/list/', camper_list, name='list'),
    path('campers/new/', camper_form_new, name='form'),
    path('campers/<int:id>/', camper_form_update, name='update'),
    path('campers/delete/<int:id>/', camper_delete, name='delete'),
    path('dashboard', dashboard, name='dashboard'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('camper.urls')),
    path('', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class District(models.Model):
    name = models.CharField(max_length=200)
    
    class Meta:
    	ordering = ['name']

    def __str__(self):
        return self.name


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	email = models.EmailField(max_length=150)
	phone = models.CharField(max_length=10)
	district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
	local_church = models.CharField(max_length=200, blank=True)
	balance = models.IntegerField(default=0)

	class Meta:
		ordering = ['district']

	def __str__(self):
		return self.user.username


@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created,	**kwargs):
	if created:
		Profile.objects.create(user=instance)
	instance.profile.save()
	

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class ProfileForm(forms.ModelForm):
	email = forms.EmailField(max_length=150, required=True)
	local_church = forms.CharField(max_length=200, required=True)
	class Meta:
		model = Profile
		fields = ('phone', 'email', 'district', 'local_church')

#############
class SignUpForm(UserCreationForm):
	username = forms.CharField(max_length=12)

	class Meta:
		model = User
		fields = ('username', 'password1', 'password2',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm, ProfileForm
from django.contrib.auth.forms import AuthenticationForm
from django.db import transaction
from django.contrib import messages


@transaction.atomic
def register(request):
	if request.method == 'POST':
		user_form = SignUpForm(request.POST)
		profile_form = ProfileForm(request.POST)
		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			username = user_form.cleaned_data.get('username')
			user.refresh_from_db() #This will load the Profile created by Signal
			profile_form = ProfileForm(request.POST, instance=user.profile) # Reload the profile form with the profile instance
			profile_form.full_clean() # Manually clean the form this time. It's implicitly called by "is_valid()" method
			profile_form.save()
			messages.info(request, "Your account has been successfully created!")
			login(request, user)
			messages.info(request, f"You are now logged in as {username}.")
			return redirect('camper:list')
		else:
			messages.error(request, "Correct the errors below")
	else:
		user_form = SignUpForm()
		profile_form = ProfileForm()
	return render(request, 'accounts/register.html', {'user_form': user_form, 'profile_form': profile_form})

def login_request(request):
	if request.method =='POST':
		form = AuthenticationForm(request=request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = (form.cleaned_data.get('password'))
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}")
				return redirect('camper:list')
			else:
				messages.error(request, "Invalid username or password")
		else:
			messages.error(request, "Invalid username or password")
	else:
		form = AuthenticationForm()
	return render(request, 'accounts/login.html', {'form': form})

def logout_request(request):
	logout(request)
	messages.info(request, "You are logged out successfully!")
	return redirect('camper:home')

templates/accounts/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <br>
    <form method="POST">
      {% csrf_token %}
      {{form|crispy}}

      <button style="background-color: yellow; color: blue" type="submit" class="btn">Log In</button>
    </form>
    <p>Don't have an account? <a href="{% url 'accounts:register' %}"><strong>register here</strong></a>!</p>
  </div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <form method="post" action="" autocomplete="on">
        {% csrf_token %}
         {{ user_form.username|as_crispy_field }}
         {{ profile_form.email|as_crispy_field }}
         {{ profile_form.phone|as_crispy_field }}
        <div class="row">
            <div class="col-md-4">
                {{ profile_form.district|as_crispy_field }}
                 </div>
                <div class="col-md-8">
                  {{ profile_form.local_church|as_crispy_field }}
                </div>
        </div>
         {{ user_form.password1|as_crispy_field }}
         {{ user_form.password2|as_crispy_field }}

          <button style="background-color: yellow; color: blue" type="submit" class="btn">Register</button>
    </form>
    <p>Already have an account? <a href="{% url 'accounts:login' %}"><strong>login here</strong></a>!</p>
</div>
{% endblock %}