camper/urls.py
from django.urls import path, include
from .views import index, camper_list, camper_form_new, camper_form_update, camper_delete, dashboard

app_name = 'camper'

urlpatterns = [
    path('', index, name='home'),
    path('campers/list/', camper_list, name='list'),
    path('campers/new/', camper_form_new, name='form'),
    path('campers/<int:id>/', camper_form_update, name='update'),
    path('campers/delete/<int:id>/', camper_delete, name='delete'),
    path('dashboard', dashboard, name='dashboard'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('camper.urls')),
    path('', include('accounts.urls')),
]

camper/models.py
from django.db import models
from accounts.models import User

class DifferentClasses(models.Model):
	name = models.CharField(max_length=200)

	class Meta:
		verbose_name_plural = 'Different Classes'

	def __str__(self):
		return self.name


class Camper(models.Model):
	MALE = 'M'
	FEMALE = 'F'
	GENDER_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    ]
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
    )
	date_of_birth = models.DateField()
	phone = models.CharField(max_length=10)
	email = models.EmailField()
	different_class = models.ForeignKey(DifferentClasses, verbose_name="Different Classes", on_delete=models.SET_NULL, null=True)
	created_by = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return f"{self.first_name} {self.last_name}"

camper/forms.py
from django import forms
from .models import Camper

class CamperForm(forms.ModelForm):
    date_of_birth = forms.DateField(help_text='Format: YYYY-MM-DD')

    class Meta:
        model = Camper
        fields = ['first_name', 'last_name','gender','date_of_birth','email','phone','different_class', 'created_by']

        labels = {
            # 'different_class': 'Different Classes'
            # 'date_of_birth': 'Date of birth (YYYY-MM-DD)'
        }

    def __init__(self, *args, **kwargs):
        super(CamperForm, self).__init__(*args, **kwargs)
        self.fields['gender'].empty_label = 'Select'
        self.fields['different_class'].empty_label = 'Select'
        

camper/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Camper
from .forms import CamperForm
from django.contrib import messages
from accounts.models import Profile


def index(request):
	return render(request, 'index.html')

### Camper list
@login_required(login_url='accounts:login')
def camper_list(request):
	user = request.user
	camper_list = Camper.objects.filter(created_by=user)
	return render(request, 'camper/list.html', {'camper_list': camper_list})

### Camper form: New
@login_required(login_url='accounts:login')
def camper_form_new(request):
	user = request.user
	user_profile = Profile.objects.get(user=user)
	user_profile_balance = user_profile.balance
	registration_fee = 80
	# Checking for balance
	if user_profile_balance < registration_fee:
			messages.info(request, f"Your balance is GHS {user_profile_balance}, which is insufficient. Kindly top up!", extra_tags='alert-danger')
			return redirect('camper:list')
	if request.method=='POST':
		form = CamperForm(request.POST, initial={'created_by': user})
		if form.is_valid():
			form.save()
			user_profile.balance = user_profile_balance - registration_fee
			user_profile.save()
			first_name = form.cleaned_data.get('first_name')
			last_name = form.cleaned_data.get('last_name')
			messages.success(request, f"{first_name} {last_name} has been successfully registered as a camper. Your balance is now GHS {user_profile.balance}.")
			return redirect('camper:list')
	else:
		form = CamperForm(initial={'created_by': user})
	return render(request, 'camper/form.html', {'form': form})

### Camper Update form
@login_required(login_url='accounts:login')
def camper_form_update(request, id):
	user = request.user
	camper = get_object_or_404(Camper, pk=id)
	if camper.created_by.id != user.id:
		messages.info(request, "You are not authorized to do this.", extra_tags='alert-danger')
		return redirect('camper:list')
	if request.method=='POST':
		form = CamperForm(request.POST, instance=camper)
		if form.is_valid():
			form.save()
			first_name = form.cleaned_data.get('first_name')
			last_name = form.cleaned_data.get('last_name')
			messages.success(request, f"{first_name} {last_name} has been successfully updated.")
			return redirect('camper:list')
	else:
		form = CamperForm(instance=camper)
	return render(request, 'camper/form.html', {'form': form})


### Camper Delete
@login_required(login_url='accounts:login')
def camper_delete(request, id):
	user = request.user
	camper = get_object_or_404(Camper, pk=id)
	if camper.created_by.id != user.id:
		messages.info(request, "You are not authorized to do this.", extra_tags='alert-danger')
		return redirect('camper:list')
	user_profile = Profile.objects.get(user=user)
	registration_fee = 80
	first_name = camper.first_name
	last_name = camper.last_name
	camper.delete()
	user_profile.balance = user_profile.balance + registration_fee
	user_profile.save()
	messages.info(request, f"{first_name} {last_name} has been deleted as a camper. Your balance is now GHS {user_profile.balance}", extra_tags='alert-danger')
	return redirect('camper:list')

### Camper Dashboard
@login_required(login_url='accounts:login')
def dashboard(request):
	user = request.user
	user_profile = Profile.objects.get(user=user)
	campers_info = Camper.objects.filter(created_by=user)
	genders = [g.gender for g in campers_info]
	gender_total = len(genders)
	gender_male = genders.count('M')
	gender_female = genders.count('F')

	return render(request, 'camper/dashboard.html', {'user_profile': user_profile, 'gender_total': gender_total, 'gender_male': gender_male, 'gender_female': gender_female})

templates/camper/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">{{ user_profile.local_church }}</h1>
  <h3 style="text-decoration: underline;">{{ user_profile.district }} District</h3>
  <p class="lead">A quick snap at your activities</p>
</div>

<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Registered Campers</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">{{ gender_total }}</h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Males: {{ gender_male }}</li>
          <li>Females: {{ gender_female }}</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary" onclick="window.location.href = '{% url 'camper:form' %}';"><i class="fas fa-plus"></i> Add camper</button>
      </div>
    </div>
   
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Balance</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">GHS {{ user_profile.balance }}</h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Registration is GHS 80 per camper</li>
          <li>Registration ends on Sun., 9th August, 2020.</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary" onclick="window.location.href = '#';"><i class="fas fa-plus"></i> Add funds</button>
      </div>
    </div>
  </div>

  
</div>

{% endblock %}

templates/camper/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<form method="post" action="" autocomplete="on">
    {% csrf_token %}
    {{ form.first_name|as_crispy_field }}
    {{ form.last_name|as_crispy_field }}
    {{ form.date_of_birth|as_crispy_field }}
     {{ form.email|as_crispy_field }}
     {{ form.phone|as_crispy_field }}
    <div class="row">
        <div class="col-md-4">
            {{ form.gender|as_crispy_field }}
             </div>
            <div class="col-md-8">
              {{ form.different_class|as_crispy_field }}
              {{ form.created_by.as_hidden }}
            </div>
    </div>
    <div class="row">
        <div class="col-md-8">
             <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database mr-2"></i>Submit</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'camper:list' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream mr-2"></i>Back to list
            </a>
        </div>
    </div>


</form>
</div>
{% endblock %}

templates/camper/list.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Full Name</td>
            <td>Gender</td>
            <td>Phone</td>
            <td>Different Class</td>
            <td>
                <a href="{% url 'camper:form' %}" class="btn btn-outline-success">
                    <i class="fas fa-plus"></i>Add New
                </a>

            </td>
        </tr>
    </thead>
    <tbody>
        {% for camper in camper_list %}
        <tr>
            <td>{{ camper.first_name }} {{ camper.last_name }}</td>
            {% if camper.gender == 'M' %}
                <td>Male</td>
            {% else %}
                <td>Female</td>
            {% endif %}
            <td>{{ camper.phone }}</td>
            <td>{{ camper.different_class }}</td>
            <td>
                <a href="{% url 'camper:update' camper.id %}" class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg"></i>
                </a>
                 <form action="{% url 'camper:delete' camper.id %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn">
                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                    </button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}